baseURL = "http://mre.coffee/"
languageCode = "en-us"
title = "Mr. Eric on Coffee"
theme = "creative-portfolio"

[params]

style = "blue"
googleAnalytics = "UA-126144146-1"
description = "Specialty Coffee Enthusiast and un-Professional"
copyright = "&copy;2018 Sauer Bros."
homequote = "Pull up a mouth, we're about to drink some coffee."
sidebarAbout = [
  "With this site, I hope to:",
  " - Help people discover the fun of coffee as a hobby<br/> - Provide value in the specialty coffee community<br/> - Combine my love for coffee and open sourced development"
]
# Contact page
   # Since this template is static, the contact form uses www.formspree.io as a
   # proxy. The form makes a POST request to their servers to send the actual
   # email. Visitors can send up to a 1000 emails each month for free.
   #
   # What you need to do for the setup?
   #
   # - set your email address under 'email' below
   # - upload the generated site to your server
   # - send a dummy email yourself to confirm your account
   # - click the confirm link in the email from www.formspree.io
   # - you're done. Happy mailing!
email = "etsauer@gmail.com"

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "Bio"
url = "about/"

[[params.navlinks]]
name = "Coffe Talk"
url = "coffee/"

[[params.navlinks]]
name = "Beyond Coffee"
url = "not-coffee/"

[[params.navlinks]]
name = "Get in touch"
url = "contact/"

[params.social]
#facebook      = "full page or profile url in facebook"
#googleplus    = "full profile url in googleplus"
email         = "etsauer@gmail.com"
#twitter       = "full profile url in twitter"
#linkedin      = "full profile url in linkedin"
#stackoverflow = "full profile url in stackoverflow"
instagram     = "https://www.instagram.com/mre_coffee/"
github        = "https://github.com/etsauer/coffee-site"
